[package]
name = "contemporary"
version = "0.1.0"
edition = "2024"

[dependencies]
contemporary_i18n = { path = "../i18n/contemporary_i18n" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "0.8"
gpui = { workspace = true }
indexmap = { workspace = true }

[build-dependencies]
contemporary_i18n_gen = { path = "../i18n/contemporary_i18n_gen" }
