[config]
i18n_dir = "dist/contemporary_toml_translations"

[application]
theme_colors = ["#6400ff", "#c800ff"]

[deployment]
application_name = "t:APPLICATION_NAME"
desktop_entry = "com.vicr123.contemporary.playground"
contemporary_base_icon = "assets/baseicon.svg"

[deployment."aarch64-apple-darwin"]
contemporary_base_icon = "assets/baseicon-mac.svg"

[deployment."x86_64-apple-darwin"]
contemporary_base_icon = "assets/baseicon-mac.svg"