[config]
i18n_dir = "dist/contemporary_toml_translations"

[application]
theme_colors = ["#6400ff", "#c800ff"]

[deployment]
application_name = "t:APPLICATION_NAME"
application_generic_name = "t:APPLICATION_GENERIC_NAME"
application_machine_name = "contemporary-playground"
organization_name = "theCheeseboard"
desktop_entry = "com.vicr123.contemporary.playground"
contemporary_base_icon = "dist/baseicon.svg"
disk_image_background = "dist/app-dmg-background.svg"
extra_info_plist_attributes = { NSRemovableVolumesUsageDescription = "t:REMOVABLE_VOLUMES_USAGE_DESCRIPTION" }
desktop_entry_categories = ["Development"]

[deployment."aarch64-apple-darwin"]
contemporary_base_icon = "dist/baseicon-mac.svg"

[deployment."x86_64-apple-darwin"]
contemporary_base_icon = "dist/baseicon-mac.svg"