name: Build on Linux
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm ]
    runs-on: ${{ matrix.os }}
    env:
      ARCH: "${{ endsWith(matrix.os, 'arm') && 'aarch64' || 'x86_64' }}"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libxkbcommon-dev libxkbcommon-x11-dev libx11-xcb-dev desktop-file-utils
          rustup update
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1
      - name: Build
        run: cargo build --verbose --release
      - name: Bundle
        run: cargo run --package cargo-cntp-bundle --bin cargo-cntp-bundle
        working-directory: playground
      - name: Deploy
        run: cargo run --package cargo-cntp-deploy --bin cargo-cntp-deploy -- --output-file "$HOME/Contemporary_Playground-$ARCH.AppImage"
        working-directory: playground
      - uses: actions/upload-artifact@v4
        with:
          name: contemporary-playground-linux-${{ env.ARCH }}
          path: "~/Contemporary_Playground-${{ env.ARCH }}.AppImage"
