name: Build on macOS
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: |
          rustup update
          rustup target install x86_64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1
      - name: Build (arm)
        run: cargo build --verbose --release
      - name: Build (x86_64)
        run: cargo build --verbose --release --target x86_64-apple-darwin
      - name: Bundle
        run: cargo run --package cargo-cntp-bundle --bin cargo-cntp-bundle -- --target x86_64-apple-darwin --target aarch64-apple-darwin
        working-directory: playground
      - name: Deploy
        run: cargo run --package cargo-cntp-deploy --bin cargo-cntp-deploy -- --target x86_64-apple-darwin --target aarch64-apple-darwin --output-file "~/Contemporary_Playground-macOS.dmg"
        working-directory: playground
      - uses: actions/upload-artifact@v4
        with:
          name: contemporary-playground-linux
          path: "~/Contemporary_Playground-macOS.dmg"
