name: Build on macOS
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: |
          rustup update
      - name: Build
        run: cargo build --verbose --release
      - name: Bundle
        run: cargo run --package cargo-cntp-bundle --bin cargo-cntp-bundle -- --target x86_64-apple-darwin --target aarch64-apple-darwin
      - name: Deploy
        run: cargo run --package cargo-cntp-deploy --bin cargo-cntp-deploy -- --target x86_64-apple-darwin --target aarch64-apple-darwin --output-file "$HOME/Contemporary_Playground-macOS.dmg"
      - uses: actions/upload-artifact@v4
        with:
          name: contemporary-playground-linux
          path: "$HOME/Contemporary_Playground-macOS.dmg"
